name: todolist123
description: Your project description goes here
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9

  cupertino_icons: ^1.0.6


# The following section is optional, depending on your project requirements